### ISSUE TITLE
Annoying tab switch

### ISSUE THREAD

**Issue by elibarzilay** [stsquad/emacs_chrome#144] opened 2018-04-11 23:03 UTC
Every time I re-start my machine or Emacs, and forget to start the edit
server for whatever reason, trying to edit some text shows the warning
about the server not working -- and when I close that message, it jumps
to the settings tab.  That's fine if it would happen once, but doing it
every time is not useful since I know immediately that I need to start
it, but meanwhile, it jumps to the new tab which is disorienting when I
need to go back later to the original tab and re-try.

So I think that it would be better to set some local flag to make this
behavior happen just once...?

**Comment by stsquad** [comment] 2018-04-16 15:24
This is a duplicate of #88 which currently has a fix in master. Could you please test and report there?

**Closed by stsquad** 2018-04-16 15:24 UTC

**Comment by elibarzilay** [comment] 2018-04-17 17:42
Sorry I missed it...
